#!/usr/bin/env python3
"""Transposed SOTA table (Guirado's request): rows = ALL the performance metrics
used in the per-workload tables, columns = methods (WBP, BB+NeoPro, AMOVMC,
EUQ-VMC), one block per workload. Composite network-aware energy, mean +/- 95% CI
(30 seeds; PlanetLab 10 traces x 30 = 300). Also paired Wilcoxon WBP vs BB+NeoPro.
Field mapping calibrated against the original per-workload tables:
  Energy     = energyWithExtraHost + (4.096*RAM+20.165)*1.1/(3600e3)   [kWh]
  Hosts      = cpuResults.totalUsedHosts
  SLA (%)    = slaOverall*100
  Migr       = numberOfMigrations
  ME (x1e7)  = vmTotalAllocatedMips / energy / 1e7    (analyze_results.py canonical)
  AvMIPS     = cpuResults.averageFreeMIPSActiveHosts  (avg available MIPS/active host)
  Disp (%)   = cpuResults.medianCPUDispersionOfActiveHosts * 100
  VMcomm     = networkPhysicalResults.totalBWUsed / 1e5   [MB x1e5]
  RAMBW      = networkPhysicalResults.totalRAMInBW / 1e5  [MB x1e5]
"""
import glob, json, os
import numpy as np
from scipy import stats

OUT = r"C:\Users\PcVIP\Desktop\_publish_vmcons\output"
HERE = os.path.dirname(os.path.abspath(__file__))
DAYS = ["20110303", "20110306", "20110309", "20110322", "20110325",
        "20110403", "20110409", "20110411", "20110412", "20110420"]
WLS = [("planetlab", "PlanetLab"), ("alibaba", "Alibaba"),
       ("materna", "Materna"), ("azure", "Microsoft Azure")]
METRICS = [("Energy Consumption (kWh)", 2), ("Total used hosts", 0),
           ("SLA Violation (\\%)", 2), ("\\# of migrations", 0),
           ("ME ratio ($\\times10^7$)", 2), ("Avg. available MIPS/active host", 0),
           ("Median CPU dispersion (\\%)", 2), ("VM communications (MB $\\times10^5$)", 2),
           ("RAM in BW (MB $\\times10^5$)", 2)]


def emig(r):
    return (4.096 * r + 20.165) * 1.1 / (3600.0 * 1000.0)


def metrics(fp):
    d = json.load(open(fp)); cs = d["cloudsimResults"]; cpu = d["cpuResults"]
    net = d["networkPhysicalResults"]
    ram = net.get("totalRAMInBW", 0)
    e = cs.get("energyWithExtraHost", cs.get("energy", 0)) + emig(ram)
    return (e,
            cpu.get("totalUsedHosts", 0),
            cs.get("slaOverall", 0) * 100,
            cs.get("numberOfMigrations", 0),
            cs.get("vmTotalAllocatedMips", 0) / e / 1e7 if e else 0,
            cpu.get("averageFreeMIPSActiveHosts", 0),
            cpu.get("medianCPUDispersionOfActiveHosts", 0) * 100,
            net.get("totalBWUsed", 0) / 1e5,
            ram / 1e5)


def collect(wl):
    tech = {"WBP": {}, "BB+NeoPro": {}, "AMOVMC": {}, "EUQ-VMC": {}}
    proph = [f"p4_pl_{d}_st" for d in DAYS] if wl == "planetlab" else [f"paper4_full_{wl}_prophet_st"]
    for fld in proph:
        for f in glob.glob(os.path.join(OUT, fld, "*_data.json")):
            c = json.load(open(f)).get("experimentConfiguration", {})
            if "bollinger" in str(c.get("hostSignalProcessing")):
                tech["WBP"][(fld, c.get("randomSeed"))] = metrics(f)
    npf = [f"np_pl_{d}_st" for d in DAYS] if wl == "planetlab" else [f"np_{wl}_st"]
    for fld in npf:
        for f in glob.glob(os.path.join(OUT, fld, "*_data.json")):
            c = json.load(open(f)).get("experimentConfiguration", {})
            tech["BB+NeoPro"][(fld, c.get("randomSeed"))] = metrics(f)
    for m, pre in [("AMOVMC", "amovmc"), ("EUQ-VMC", "euqvmc")]:
        folders = [f"{pre}_pl_{d}" for d in DAYS] if wl == "planetlab" else [f"{pre}_{wl}"]
        for fld in folders:
            for f in glob.glob(os.path.join(OUT, fld, "*_data.json")):
                c = json.load(open(f)).get("experimentConfiguration", {})
                tech[m][(fld.replace("np_", "").replace("amovmc_", "").replace("euqvmc_", ""),
                         c.get("randomSeed"))] = metrics(f)
    return tech


def cell(vals, i, dec):
    a = np.array([v[i] for v in vals], float); n = len(a)
    m = a.mean(); ci = stats.t.ppf(0.975, n - 1) * a.std(ddof=1) / np.sqrt(n)
    if dec == 0:
        return f"{m:.0f}\\,$\\pm$\\,{ci:.0f}", m
    return f"{m:.2f}\\,$\\pm$\\,{ci:.2f}", m

ORDER = ["WBP", "BB+NeoPro", "AMOVMC", "EUQ-VMC"]
lines = [r"% ===== TRANSPOSED SOTA comparison (all workload-table metrics) =====",
         r"% generated by SOTA/emit_transposed.py — composite energy, mean +/- CI95"]
md = ["# Transposed SOTA table (all metrics) — composite energy, mean ± CI95\n"]
wilc = ["\n## Paired Wilcoxon WBP vs BB+NeoPro (raw p; lower-is-better metrics)\n"]

for wl, disp in WLS:
    t = collect(wl)
    lines.append(r"\begin{table*}[!ht]" if wl == "planetlab" else "")
    md.append(f"\n## {disp}\n")
    md.append("| Metric | " + " | ".join(ORDER) + " |")
    md.append("|---|---|---|---|---|")
    blk = [r"\multicolumn{5}{l}{\textbf{%s}} \\" % disp, r"\hline"]
    for mi, (label, dec) in enumerate(METRICS):
        row_tex, row_md = [], []
        for m in ORDER:
            c, mean = cell(list(t[m].values()), mi, dec)
            row_tex.append(c); row_md.append(c.replace("\\,$\\pm$\\,", " ± ").replace("\\%", "%").replace("$\\times10^", "e").replace("$", ""))
        blk.append(f"{label} & " + " & ".join(row_tex) + r" \\")
        md.append(f"| {label} | " + " | ".join(row_md) + " |")
    blk.append(r"\hline")
    lines += blk
    # wilcoxon WBP vs BB+NeoPro — normalise folder names to (trace/wl, seed)
    def norm(k):
        fld, seed = k
        for pre in ("p4_pl_", "np_pl_", "np_", "paper4_full_"):
            if fld.startswith(pre):
                fld = fld[len(pre):]
        return (fld.replace("_prophet_st", "").replace("_st", ""), seed)
    a_map = {norm(k): v for k, v in t["WBP"].items()}
    b_map = {norm(k): v for k, v in t["BB+NeoPro"].items()}
    keys = sorted(set(a_map) & set(b_map))
    t = dict(t); t["WBP"] = a_map; t["BB+NeoPro"] = b_map
    wilc.append(f"**{disp}** (n={len(keys)} paired):")
    for mi, lbl in [(0, "Energy"), (2, "SLA"), (3, "migr"), (8, "RAM")]:
        xa = np.array([t["WBP"][k][mi] for k in keys]); xb = np.array([t["BB+NeoPro"][k][mi] for k in keys])
        p = stats.wilcoxon(xa, xb).pvalue if not np.allclose(xa, xb) else float("nan")
        win = "WBP" if np.median(xa - xb) < 0 else "BB+NeoPro"
        wilc.append(f"  - {lbl}: winner {win}, p={p:.1e}")
open(os.path.join(HERE, "transposed_table.tex"), "w", encoding="utf-8").write("\n".join(lines))
open(os.path.join(HERE, "transposed_table.md"), "w", encoding="utf-8").write("\n".join(md + wilc))
print("\n".join(md + wilc))
print("\n[saved] SOTA/transposed_table.tex and .md")
